[project]
name = "financas_crew"
version = "0.1.0"
description = "financas_crew using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[google-genai,tools]>=1.15.15,<2.0.0",
    "fastapi>=0.141.1",
    "uvicorn>=0.52.1",
]

[project.scripts]
financas_crew = "financas_crew.main:run"
run_crew = "financas_crew.main:run"
train = "financas_crew.main:train"
replay = "financas_crew.main:replay"
test = "financas_crew.main:test"
run_with_trigger = "financas_crew.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
project_id = "11a41de2-a383-49f9-bd43-71dd233060ef"
